export const ADD_POKEMON = 'ADD_POKEMON';
export const CREATE_POKEMON = 'CREATE_POKEMON';
export const DELETE_POKEMON = 'DELETE_POKEMON';
export const TYPE_FILTER = 'TYPE_FILTER';
export const ORIGIN_FILTER = 'ORIGIN_FILTER';
export const NAME_ORDER = 'NAME_ORDER';
export const ATTACK_ORDER = 'ATTACK_ORDER';